on:
  push:
    branches:
      - master
name: publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Up NPM
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - run: yarn
    - run: yarn build

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build